[tool.poetry]
name = "aafc-data-catalogue-scanner"
version = "0.1.0"
description = ""
authors = ["a-taillardat <alexis.taillardat@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pandas = "^2.2.2"
numpy = "^2.0.0"
requests = "^2.32.3"
urllib3 = "^2.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
